### ISSUE TITLE
Errors While Running the Batch File

### ISSUE THREAD

**Issue by RevanFan1** [DarthParametric/TSL_Blade_Stuck_On_Fix_For_Oldflash_Lightsaber_Replacement_Hilts#1]
Every time I  try to run the batch file, when it begins the patching process, I get the following error:

"'hpatchz' is not recognized as an internal or external command, operable program or batch file."

I'm on Windows 10 Home 64-bit, but I decided anyway to follow part of the other-OS instructions and download the HDiffPatch files, moved them to the Override folder, and ran the batch file again. This time, when patching, I got this error.

"check hpatch_tFileStreamInput_open(&diffData,diffFileName) error!
input diffFile open read ERROR!"

Any ideas why this is happening and how to fix it?

**Comment by DarthParametric** [comment]
Looks like I forgot to attach the actual release zip, so it lacked the binaries. Fixed now. Grab [TSL_Blade_Fix_For_Oldflash_Hilts_v1.2.1.zip](https://github.com/DarthParametric/TSL_Blade_Stuck_On_Fix_For_Oldflash_Lightsaber_Replacement_Hilts/releases/latest).
